# Generated by Django 5.2.10 on 2026-01-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_record_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.category'),
        ),
    ]
