# Generated by Django 5.2.10 on 2026-01-26 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_record_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.IntegerField(max_length=11, validators=[django.core.validators.MinValueValidator(11)]),
        ),
    ]
