# Generated by Django 5.2.10 on 2026-01-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_record_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Category',
            new_name='category',
        ),
    ]
