# Generated by Django 5.2.10 on 2026-02-11 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_category_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
