# Generated by Django 5.2.10 on 2026-05-13 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_record_tall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tall',
        ),
        migrations.AlterField(
            model_name='record',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
