# Generated by Django 5.2.10 on 2026-05-13 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_record_tall_alter_record_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
